version: '3.1'

services:
  nginx:
    build:
      context: ./
      dockerfile: Dockerfile_nginx
    container_name: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/localhost.crt:/etc/ssl/certs/localhost.crt
      - ./nginx/localhost.key:/etc/ssl/localhost.key
    ports:
      - 80:80
      - 443:443
    networks:
      - my-network
    depends_on:
      - flask
  flask:
    build:
      context: ./
      dockerfile: Dockerfile_flask
    container_name: flask
    command: gunicorn --chdir app --bind 0.0.0.0:8000 --workers 1 "wsgi:app"
    networks:
      my-network:
        aliases:
          - flask-app
    env_file:
      - .env
networks:
  my-network: